- src/main/resources/application.properties
application.properties 관련 설정 코드 작성
현재 GCP를 사용중이기에 MairaDB로 작성됨.
추후 MySQL로 변경할 예정
> application.properties DB 관련 설정

- build.gradle
- src/main/java/com/sw/journal/journalcrawlerpublisher/config/SecurityConfig.java
- src/main/java/com/sw/journal/journalcrawlerpublisher/constant/UserRole.java
- src/main/java/com/sw/journal/journalcrawlerpublisher/controller/UserController.java
- src/main/java/com/sw/journal/journalcrawlerpublisher/controller/test.java
- src/main/java/com/sw/journal/journalcrawlerpublisher/domain/Category.java
- src/main/java/com/sw/journal/journalcrawlerpublisher/domain/CrawledArticle.java
- src/main/java/com/sw/journal/journalcrawlerpublisher/domain/OutArticle.java
- src/main/java/com/sw/journal/journalcrawlerpublisher/domain/User.java
- src/main/java/com/sw/journal/journalcrawlerpublisher/domain/UserCreateForm.java
- src/main/java/com/sw/journal/journalcrawlerpublisher/repository/UserRepository.java
- src/main/java/com/sw/journal/journalcrawlerpublisher/repository/test.java
- src/main/java/com/sw/journal/journalcrawlerpublisher/service/UserService.java
- src/main/java/com/sw/journal/journalcrawlerpublisher/service/test.java
- src/main/resources/application-test.properties
- src/main/resources/templates/layouts/base_layout.html
- src/main/resources/templates/signup_form.html
- src/test/java/com/sw/journal/journalcrawlerpublisher/repository/UserRepositoryTest.java
> 회원가입 기능 테스트 작성(유저 생성, 유저 중복 검사)

- src/main/java/com/sw/journal/journalcrawlerpublisher/domain/ArticleRank.java
- src/main/java/com/sw/journal/journalcrawlerpublisher/domain/Category.java
- src/main/java/com/sw/journal/journalcrawlerpublisher/domain/Comment.java
- src/main/java/com/sw/journal/journalcrawlerpublisher/domain/CrawledArticle.java
- src/main/java/com/sw/journal/journalcrawlerpublisher/domain/Member.java
- src/main/java/com/sw/journal/journalcrawlerpublisher/domain/OurArticle.java
- src/main/java/com/sw/journal/journalcrawlerpublisher/domain/OutArticle.java
- src/main/java/com/sw/journal/journalcrawlerpublisher/domain/Report.java
- src/main/java/com/sw/journal/journalcrawlerpublisher/domain/Tag.java
- src/main/java/com/sw/journal/journalcrawlerpublisher/domain/User.java
- src/main/java/com/sw/journal/journalcrawlerpublisher/domain/UserBookmarkedArticle.java
- src/main/java/com/sw/journal/journalcrawlerpublisher/domain/UserBookmarkedArticleId.java
- src/main/java/com/sw/journal/journalcrawlerpublisher/domain/UserFavoriteCategory.java
- src/main/java/com/sw/journal/journalcrawlerpublisher/domain/UserFavoriteCategoryId.java
- src/main/java/com/sw/journal/journalcrawlerpublisher/repository/ArticleRankRepository.java
- src/main/java/com/sw/journal/journalcrawlerpublisher/repository/CategoryRepository.java
- src/main/java/com/sw/journal/journalcrawlerpublisher/repository/CommentRepository.java
- src/main/java/com/sw/journal/journalcrawlerpublisher/repository/MemberRepository.java
- src/main/java/com/sw/journal/journalcrawlerpublisher/repository/OurArticleRepository.java
- src/main/java/com/sw/journal/journalcrawlerpublisher/repository/ReportRepository.java
- src/main/java/com/sw/journal/journalcrawlerpublisher/repository/TagRepository.java
- src/main/java/com/sw/journal/journalcrawlerpublisher/repository/UserBookmarkedArticleRepository.java
- src/main/java/com/sw/journal/journalcrawlerpublisher/repository/UserFavoriteCategoryRepository.java
- src/main/java/com/sw/journal/journalcrawlerpublisher/repository/test.java
> [PR] ERD 및 DataDictionary를 바탕으로 한 Domain 생성 및 Domain에 따른 기본 Repository 생성 PR 요청

- src/main/java/com/sw/journal/journalcrawlerpublisher/domain/Category.java
- src/main/java/com/sw/journal/journalcrawlerpublisher/domain/Comment.java
- src/main/java/com/sw/journal/journalcrawlerpublisher/domain/Member.java
- src/main/java/com/sw/journal/journalcrawlerpublisher/domain/OurArticle.java
- src/main/java/com/sw/journal/journalcrawlerpublisher/domain/Report.java
- src/main/java/com/sw/journal/journalcrawlerpublisher/domain/Tag.java
- src/main/java/com/sw/journal/journalcrawlerpublisher/domain/TagArticle.java
- src/main/java/com/sw/journal/journalcrawlerpublisher/domain/UserBookmarkedArticle.java
- src/main/java/com/sw/journal/journalcrawlerpublisher/domain/UserBookmarkedArticleId.java
- src/main/java/com/sw/journal/journalcrawlerpublisher/domain/UserFavoriteCategory.java
- src/main/java/com/sw/journal/journalcrawlerpublisher/domain/UserFavoriteCategoryId.java
- src/main/java/com/sw/journal/journalcrawlerpublisher/repository/ArticleRankRepository.java
- src/main/java/com/sw/journal/journalcrawlerpublisher/repository/CategoryRepository.java
- src/main/java/com/sw/journal/journalcrawlerpublisher/repository/CommentRepository.java
- src/main/java/com/sw/journal/journalcrawlerpublisher/repository/MemberRepository.java
- src/main/java/com/sw/journal/journalcrawlerpublisher/repository/OurArticleRepository.java
- src/main/java/com/sw/journal/journalcrawlerpublisher/repository/ReportRepository.java
- src/main/java/com/sw/journal/journalcrawlerpublisher/repository/TagArticleRepository.java
- src/main/java/com/sw/journal/journalcrawlerpublisher/repository/TagRepository.java
- src/main/java/com/sw/journal/journalcrawlerpublisher/repository/UserBookmarkedArticleRepository.java
- src/main/java/com/sw/journal/journalcrawlerpublisher/repository/UserFavoriteCategoryRepository.java
ERD 관련 수정 + image 테이블을 위한 속성 추가
> DB table 의 속성 및 PK 이름 일괄되게 수정 및

- src/main/java/com/sw/journal/journalcrawlerpublisher/controller/OurArticleController.java
- src/main/java/com/sw/journal/journalcrawlerpublisher/domain/Category.java
- src/main/java/com/sw/journal/journalcrawlerpublisher/domain/OurArticle.java
- src/main/java/com/sw/journal/journalcrawlerpublisher/domain/Tag.java
- src/main/java/com/sw/journal/journalcrawlerpublisher/repository/CategoryRepository.java
- src/main/java/com/sw/journal/journalcrawlerpublisher/repository/OurArticleRepository.java
- src/main/java/com/sw/journal/journalcrawlerpublisher/repository/TagRepository.java
- src/main/java/com/sw/journal/journalcrawlerpublisher/service/OurArticleService.java
> 카테고리,태그별 검색 기능 구현

- build.gradle
- src/main/java/com/sw/journal/journalcrawlerpublisher/crawler/CioCrawler.java
- src/main/java/com/sw/journal/journalcrawlerpublisher/domain/ArticleRank.java
- src/main/java/com/sw/journal/journalcrawlerpublisher/domain/Category.java
- src/main/java/com/sw/journal/journalcrawlerpublisher/domain/Image.java
- src/main/java/com/sw/journal/journalcrawlerpublisher/domain/OurArticle.java
- src/main/java/com/sw/journal/journalcrawlerpublisher/repository/ArticleRankRepository.java
- src/main/java/com/sw/journal/journalcrawlerpublisher/repository/CategoryRepository.java
- src/main/java/com/sw/journal/journalcrawlerpublisher/repository/ImageRepository.java
- src/main/java/com/sw/journal/journalcrawlerpublisher/repository/OurArticleRepository.java
- src/main/java/com/sw/journal/journalcrawlerpublisher/repository/TagRepository.java
ArticleRank, Category, OurArticle, Tag, TagArticle 변경
Image 도메인 추가
Cio 크롤링 추가
> Cio 뉴스 크롤링

- src/main/java/com/sw/journal/journalcrawlerpublisher/domain/OurArticle.java
- src/test/java/com/sw/journal/journalcrawlerpublisher/crawler/CioCrawlerTest.java
> Cio 뉴스 크롤링 테스트 커밋

- src/main/java/com/sw/journal/journalcrawlerpublisher/crawler/ItWorldCrawler.java
- src/test/java/com/sw/journal/journalcrawlerpublisher/crawler/CioCrawlerTest.java
- src/test/java/com/sw/journal/journalcrawlerpublisher/crawler/ItWorldCrawlerTest.java
> IT World 뉴스 크롤링 및 테스트 커밋

- src/main/java/com/sw/journal/journalcrawlerpublisher/controller/MemberRestController.java
- src/main/java/com/sw/journal/journalcrawlerpublisher/domain/Member.java
- src/main/java/com/sw/journal/journalcrawlerpublisher/domain/ProfileImage.java
- src/main/java/com/sw/journal/journalcrawlerpublisher/repository/ProfileImageRepostiory.java
- src/main/java/com/sw/journal/journalcrawlerpublisher/repository/UserFavoriteCategoryRepository.java
- src/main/java/com/sw/journal/journalcrawlerpublisher/service/MemberService.java
- src/main/java/com/sw/journal/journalcrawlerpublisher/service/ProfileImageService.java
1. 선호 카테고리 기능 수정
- 선호 카테고리가 편집되지 않고 기존의 선호 카테고리 리스트에 추가되는 문제 수정함
- userFavoriteCategoryRepository 클래스에서 findByMember 메소드와 findByMemberId 메소드가 있었는데
findByMemberId 메소드는 필요없을거 같아서 삭제함
2. 프로필 사진 변경 기능 구현
- 컨트롤러에서 MultipartFile 객체를 인자로 받아서 이미지 파일을 서버 및 DB에 저장하는 방식으로 구현함
> [PR] 프로필 사진 변경 기능 구현

- src/main/java/com/sw/journal/journalcrawlerpublisher/controller/MemberRestController.java
- src/main/java/com/sw/journal/journalcrawlerpublisher/domain/ChangePwDTO.java
- src/main/java/com/sw/journal/journalcrawlerpublisher/domain/DuplicationCheckDTO.java
- src/main/java/com/sw/journal/journalcrawlerpublisher/domain/MypageDTO.java
- src/main/java/com/sw/journal/journalcrawlerpublisher/domain/VerificationDTO.java
- src/main/java/com/sw/journal/journalcrawlerpublisher/service/MemberService.java
- MemberRestController 대폭 수정
- 엔드포인트 일부 통합
- Post 메소드 인자 RequestParam -> RequestBody로 수정
(MultipartFile은 RequestBody로 안된다길래 제외)
- RequestBody로 전달하기 위한 DTO 클래스들 생성
> [PR] MemberRestController 수정 및 DTO클래스들 생성

- build.gradle
- src/main/java/com/sw/journal/journalcrawlerpublisher/config/RedisConfig.java
- src/main/java/com/sw/journal/journalcrawlerpublisher/crawler/CioCrawler.java
- src/main/java/com/sw/journal/journalcrawlerpublisher/crawler/ItWorldCrawler.java
- src/main/java/com/sw/journal/journalcrawlerpublisher/domain/Image.java
- src/main/java/com/sw/journal/journalcrawlerpublisher/domain/OurArticle.java
- src/main/java/com/sw/journal/journalcrawlerpublisher/repository/ArticleRankRepository.java
- src/main/java/com/sw/journal/journalcrawlerpublisher/service/ArticleRankService.java
- src/main/resources/application.properties
- src/test/java/com/sw/journal/journalcrawlerpublisher/service/ArticleRankServiceTest.java
> Redis 조작 설정 및 함수

- src/main/java/com/sw/journal/journalcrawlerpublisher/controller/MailController.java
- src/main/java/com/sw/journal/journalcrawlerpublisher/controller/MemberRestController.java
- src/main/java/com/sw/journal/journalcrawlerpublisher/service/MailService.java
- src/main/java/com/sw/journal/journalcrawlerpublisher/service/MemberService.java
- Google SMTP 서비스 탑재!!!!
- MemberRestController랑 MemberService에 있던 이메일 관련 코드들 
MailController, MailService로 분리
> [PR] Google SMTP 서비스 탑재

- build.gradle
- src/main/java/com/sw/journal/journalcrawlerpublisher/controller/MemberRestController.java
- src/main/java/com/sw/journal/journalcrawlerpublisher/domain/MypageDTO.java
- src/main/java/com/sw/journal/journalcrawlerpublisher/service/ProfileImageService.java
- src/main/resources/application.properties
- 프로필 이미지 관련 기능 리액트와 통합하기 위해 이것저것 수정  
- 이미지 저장 경로 변경 (로컬 경로->프로젝트 내부 경로(src/main/resources/images/))
- React에서 이미지를 표시하기 위해 이미지를 다운로드할 수 있는 엔드포인트 추가
- 프로필 이미지 URL이 표시되게 MypageDTO 수정
- application.properties에 Google SMTP, ProfileImage Path을 위한 설정 추가
- build.gradle에 이메일 인증번호 발송 관련 라이브러리 추가
> [PR] 프로필 이미지와 관련된 코드 수정 및 추가

- src/main/java/com/sw/journal/journalcrawlerpublisher/controller/MemberRestController.java
- src/main/java/com/sw/journal/journalcrawlerpublisher/crawler/BrunchStoryCrawler.java
- login 엔드포인트 JSessionID 발급하도록 수정
- BranchStroyCrawler 파일은 무시해주세요..제 공부용..
> [PR] login 기능 수정

- src/main/java/com/sw/journal/journalcrawlerpublisher/config/SecurityConfig.java
- src/main/java/com/sw/journal/journalcrawlerpublisher/controller/MemberRestController.java
- src/main/java/com/sw/journal/journalcrawlerpublisher/domain/Member.java
- src/main/java/com/sw/journal/journalcrawlerpublisher/domain/MypageDTO.java
- src/main/java/com/sw/journal/journalcrawlerpublisher/domain/UserFavoriteCategoryDTO.java
- src/main/java/com/sw/journal/journalcrawlerpublisher/service/ProfileImageService.java
- Member 테이블에 boolean alarm 컬럼 추가
- 선호 카테고리 편집 기능 수정
-  엔드포인트 수정 (@RequestBody로 넘겨받는 인자를 리스트 -> DTO로 수정)
-  선호 카테고리 DTO 생성
- 로그아웃, 알람 설정 엔드포인트 추가
- MypageDTO에 생성 날짜 추가함
- 프로필 이미지 저장 경로를 절대 경로에서 상대 경로로 수정
> [PR] 리액트 - SPRING 연동을 위한 수정

- src/main/java/com/sw/journal/journalcrawlerpublisher/config/jwt/test.java
- src/main/java/com/sw/journal/journalcrawlerpublisher/constant/test.java
- src/main/java/com/sw/journal/journalcrawlerpublisher/controller/ArticleRankController.java
- src/main/java/com/sw/journal/journalcrawlerpublisher/controller/MailController.java
- src/main/java/com/sw/journal/journalcrawlerpublisher/controller/MemberRestController.java
- src/main/java/com/sw/journal/journalcrawlerpublisher/controller/OurArticleController.java
- src/main/java/com/sw/journal/journalcrawlerpublisher/controller/RecommendedArticleController.java
- src/main/java/com/sw/journal/journalcrawlerpublisher/controller/test.java
- src/main/java/com/sw/journal/journalcrawlerpublisher/domain/UserBookmarkedArticle.java
- src/main/java/com/sw/journal/journalcrawlerpublisher/dto/ChangePwDTO.java
- src/main/java/com/sw/journal/journalcrawlerpublisher/dto/DuplicationCheckDTO.java
- src/main/java/com/sw/journal/journalcrawlerpublisher/dto/LoginDTO.java
- src/main/java/com/sw/journal/journalcrawlerpublisher/dto/MemberDTO.java
- src/main/java/com/sw/journal/journalcrawlerpublisher/dto/MypageDTO.java
- src/main/java/com/sw/journal/journalcrawlerpublisher/dto/OurArticleWithTagsDTO.java
- src/main/java/com/sw/journal/journalcrawlerpublisher/dto/UserFavoriteCategoryDTO.java
- src/main/java/com/sw/journal/journalcrawlerpublisher/dto/VerificationDTO.java
- src/main/java/com/sw/journal/journalcrawlerpublisher/repository/OurArticleRepository.java
- src/main/java/com/sw/journal/journalcrawlerpublisher/repository/ProfileImageRepository.java
- src/main/java/com/sw/journal/journalcrawlerpublisher/service/MailService.java
- src/main/java/com/sw/journal/journalcrawlerpublisher/service/OurArticleService.java
- src/main/java/com/sw/journal/journalcrawlerpublisher/service/ProfileImageService.java
- src/main/java/com/sw/journal/journalcrawlerpublisher/service/RecommendArticleService.java
- src/main/java/com/sw/journal/journalcrawlerpublisher/service/TagService.java
- src/main/java/com/sw/journal/journalcrawlerpublisher/service/test.java
- test 클래스 삭제, dto 패키지 이동, 중복코드 모듈화, 의존성 주입방식 변경 ( 필드 -> 생성자 )
- 없음
- 수정 부분에 수정 날짜, 내 이름, 수정내용 적어놨습니다
- 데이터 구조 변경한 게 없어서 DDL은 없습니다
- 없음
- [V] 코드가 정상적으로 작동하는지 확인했습니다.
- [V] 모든 문서를 작성했습니다.
- [V] PR 템플릿의 모든 체크박스를 채웠습니다.
> (is 167) code refactor

- src/main/java/com/sw/journal/journalcrawlerpublisher/controller/OurArticleController.java
- src/main/java/com/sw/journal/journalcrawlerpublisher/controller/RecommendedArticleController.java
- src/main/java/com/sw/journal/journalcrawlerpublisher/repository/TagArticleRepository.java
모든 아티클을 불러오는 시간을 개선했습니다
8초 -> 2초
> [기능 개선]article-all 쿼리 시간 개선

- build.gradle
- src/main/java/com/sw/journal/journalcrawlerpublisher/config/WebConfig.java
- src/main/java/com/sw/journal/journalcrawlerpublisher/crawler/CioCrawler.java
- src/main/java/com/sw/journal/journalcrawlerpublisher/crawler/ItWorldCrawler.java
- src/main/java/com/sw/journal/journalcrawlerpublisher/domain/Article.java
- src/main/java/com/sw/journal/journalcrawlerpublisher/domain/UserBookmarkedArticle.java
- src/main/resources/application.properties
- src/test/java/com/sw/journal/journalcrawlerpublisher/crawler/CioCrawlerTest.java
- src/test/java/com/sw/journal/journalcrawlerpublisher/crawler/ItWorldCrawlerTest.java
DB itScribe로 변경
기사와 카테고리 관계 1:N으로 변경
북마크 테이블 복합키 -> 단일키 수정
크롤링 수행 시 이미 정해진 카테고리 내에서 랜덤 값으로 하나 지정됨
> DB 수정, 크롤링 수정

- src/main/java/com/sw/journal/journalcrawlerpublisher/controller/UserBookmarkedArticleController.java
- src/main/java/com/sw/journal/journalcrawlerpublisher/repository/UserBookmarkedArticleRepository.java
> 북마크 삭제 API 추가

- src/main/java/com/sw/journal/journalcrawlerpublisher/controller/AdminController.java
- src/main/java/com/sw/journal/journalcrawlerpublisher/controller/MemberRestController.java
- src/main/java/com/sw/journal/journalcrawlerpublisher/domain/Ban.java
- src/main/java/com/sw/journal/journalcrawlerpublisher/dto/BanDTO.java
- src/main/java/com/sw/journal/journalcrawlerpublisher/repository/BanRepository.java
- src/main/java/com/sw/journal/journalcrawlerpublisher/repository/CommentRepository.java
- src/main/java/com/sw/journal/journalcrawlerpublisher/scheduler/BanCleanupScheduler.java
- src/main/java/com/sw/journal/journalcrawlerpublisher/service/AdminService.java
- src/main/java/com/sw/journal/journalcrawlerpublisher/service/MemberService.java
(1) Ban(유저 제재) 엔티티 추가
(2) Ban(유저 제재) DTO 추가
(3) Ban(유저 제재) Repository 추가
(4) AdminController:
-- 밴당한 유저 리스트 조회 및 삭제
(5) AdminService:
-- 컨트롤러에 따른 수정
[ Member Controller/Service 일부 수정 ]
(1) MemberRestController:
-- 유저 Login 시에 반환값에 role 을 추가
-- 유저 Login 시에 정지된 계정일시, 정지종료일 안내
(2) MemberService: 컨트롤러에 따른 수정
[ etc ]
-- 스케줄러: 하루기준으로 유저를 제재 -> 매일 자정에 정지된 유저 List 를 확인하고 해제
-- 프론트 페이지 구현완료
-- 기사 수정/삭제 기능 미구현 상태로 추후 재구현 예정
> [ 유저 계정제재 기능]

- src/main/java/com/sw/journal/journalcrawlerpublisher/controller/RedisController.java
- src/main/java/com/sw/journal/journalcrawlerpublisher/controller/UserBookmarkedArticleController.java
- src/main/java/com/sw/journal/journalcrawlerpublisher/repository/UserBookmarkedArticleRepository.java
- src/main/java/com/sw/journal/journalcrawlerpublisher/service/BookmarkService.java
> 북마크 기사 API 수정

- src/main/java/com/sw/journal/journalcrawlerpublisher/config/RedisConfig.java
- src/main/java/com/sw/journal/journalcrawlerpublisher/controller/RedisController.java
- src/main/java/com/sw/journal/journalcrawlerpublisher/service/ArticleRankService.java
- src/test/java/com/sw/journal/journalcrawlerpublisher/service/ArticleRankServiceTest.java
> Redis Template 수정

- src/main/java/com/sw/journal/journalcrawlerpublisher/aspect/LogAspect.java
- src/main/java/com/sw/journal/journalcrawlerpublisher/controller/ArticleController.java
- src/main/java/com/sw/journal/journalcrawlerpublisher/controller/UserBookmarkedArticleController.java
- src/main/java/com/sw/journal/journalcrawlerpublisher/dto/MemberViewArticleDTO.java
- src/main/java/com/sw/journal/journalcrawlerpublisher/logController/ArticleSearchLogger.java
- src/main/java/com/sw/journal/journalcrawlerpublisher/logController/ArticleViewLogger.java
- src/main/java/com/sw/journal/journalcrawlerpublisher/logController/CommentDeleteLogger.java
- src/main/java/com/sw/journal/journalcrawlerpublisher/service/ArticleService.java
- src/main/resources/itScribe-log-control.xml
+ 댓글 삭제 시 로그 저장
+ 댓글 삭제 로직 수행 전 댓글에 관한 정보와 댓글 작성자의 정보를 로그로 저장
+ 기사 검색 시 로그 저장
+ 기사 검색 후 검색어와 검색한 사용자의 정보를 로그로 저장
> 댓글 삭제 시 로그 저장, 기사 검색 시 로그 저장

- src/main/java/com/sw/journal/journalcrawlerpublisher/config/AsyncConfig.java
- src/test/java/com/sw/journal/journalcrawlerpublisher/crawler/CloudTechNewsCrawlerTest.java
- src/test/java/com/sw/journal/journalcrawlerpublisher/crawler/allarticle/CloudTechNewsAllCrawler.java
- CloudTechNews 사이트에 전체 뉴스 크롤링 ( 약 100개 ) 후 DB에 저장
- CloudTechNews 크롤러 구현
- CloudTechNews 크롤러에 멀티스레딩과 Reentrant 분산락 적용
- 크롤러의 속도 향상을 위해 멀티스레딩 방식을 도입
- Reentrant vs Syncronzied : Reentrant 방식이 Syncronized 보다 유연하고, 실패하면 재시도하고 타임 아웃을 정할 수 있는 이점을 가지고 있어서 Reentrant 락 방식을 채택
- 멀티스레딩에 따른 동시성 제어 필요
1.  공유자원 : 데이터베이스 레포지토리에 대한 접근 ( articleRepo, categoryRepo, imageRepo, articleRankRepo ),
에 대해서, 동시에 동일한 데이터를 쓰려고 할 때  데이터 무결성 문제를 일으킬 수 있음
2.  데이터 일관성을 유지해야하는 부분 :  데이터를 읽고 쓰는 부분 
1. 기사 중복검사
2. 데이터 저장 및 업데이트 ( 동시에 저장 시 충돌 )
3. 이벤트를 카프카로 발행하는 부분
3. 락을 건 부분 :  1, 2번 에 대한 작업에 해당하는 코드 블록에 Reentrant 락을 검
- 기사 중복 검사 : articleRepository.findBySource(articleUrl)
- 기사 데이터 저장 : articleRepository.save(article)
- 이미지 저장 : imageRepository.save(image)
- 기사 랭크 저장 : articleRankRepository.save(articleRank)
- 카프카 이벤트 …
> (jira 186) crawler
